// HBR Enums

export enum CardStatus {
	None = 0,
	Owned
}

export enum CardStatusURL {
	NONE = 0,
	OWNED
}

export enum CardRarity {
	A = 1,
	S,
	SS
}

export enum CharacterTeam {
	"31A" = 0,
	"31B",
	"31C",
	"31D",
	"31E",
	"31F",
	"31X",
	"30G",
	"Angel Beats"
}

export enum CharacterTeamName {
	"31A" = 0,
	"31B",
	"31C",
	"31D",
	"31E",
	"31F",
	"31X",
	"30G",
	"Angel Beats!"
}

export enum CharacterTeamURL {
	"31A" = 0,
	"31B",
	"31C",
	"31D",
	"31E",
	"31F",
	"31X",
	"30G",
	ANGELBEATS
}

export enum AbilityType {
	Hp = 0,
	Dp,
	Sp,
	Power,
	Wisdom,
	Dexterity,
	Spirit,
	Luck,
	Toughness,
	Skill,
	SpRecovery,
	PassiveSkill,
	CriticalRate,
	ParamAll,
	PursuitRate,
	Token,
	PursuitRateSlash,
	PursuitRateStab,
	PursuitRateStrike,
	SkillGrowthAbility,
	ElementResist = 50,
	DebuffResist = 51,
	SkillLimitBreak = 60,
	Generalize = 61
}

export enum AbilityValueType {
	Ratio = 0,
	RealNumber,
	Addition
}

export enum AutoSkillType {
	None = 0,
	Pursuit,
	Cover,
	Counter,
	CounterBlock
}

export enum BuffCategory {
	None = 0,
	AttackUp_Count,
	AttackUpFire_Count,
	AttackUpIce_Count,
	AttackUpThunder_Count,
	AttackUpLight_Count,
	AttackUpDark_Count,
	AttackUpSlash_Count,
	AttackUpStab_Count,
	AttackUpStrike_Count,
	AttackUp_Turn,
	AttackUpFire_Turn,
	AttackUpIce_Turn,
	AttackUpThunder_Turn,
	AttackUpLight_Turn,
	AttackUpDark_Turn,
	AttackUpSlash_Turn,
	AttackUpStab_Turn,
	AttackUpStrike_Turn,
	AttackDown_Count,
	AttackDownFire_Count,
	AttackDownIce_Count,
	AttackDownThunder_Count,
	AttackDownLight_Count,
	AttackDownDark_Count,
	AttackDownSlash_Count,
	AttackDownStab_Count,
	AttackDownStrike_Count,
	AttackDown_Turn,
	AttackDownFire_Turn,
	AttackDownIce_Turn,
	AttackDownThunder_Turn,
	AttackDownLight_Turn,
	AttackDownDark_Turn,
	AttackDownSlash_Turn,
	AttackDownStab_Turn,
	AttackDownStrike_Turn,
	DefenseUp_Count,
	DefenseUpFire_Count,
	DefenseUpIce_Count,
	DefenseUpThunder_Count,
	DefenseUpLight_Count,
	DefenseUpDark_Count,
	DefenseUpSlash_Count,
	DefenseUpStab_Count,
	DefenseUpStrike_Count,
	DefenseUp_Turn,
	DefenseUpFire_Turn,
	DefenseUpIce_Turn,
	DefenseUpThunder_Turn,
	DefenseUpLight_Turn,
	DefenseUpDark_Turn,
	DefenseUpSlash_Turn,
	DefenseUpStab_Turn,
	DefenseUpStrike_Turn,
	DefenseDown_Count,
	DefenseDownFire_Count,
	DefenseDownIce_Count,
	DefenseDownThunder_Count,
	DefenseDownLight_Count,
	DefenseDownDark_Count,
	DefenseDownSlash_Count,
	DefenseDownStab_Count,
	DefenseDownStrike_Count,
	DefenseDown_Turn,
	DefenseDownFire_Turn,
	DefenseDownIce_Turn,
	DefenseDownThunder_Turn,
	DefenseDownLight_Turn,
	DefenseDownDark_Turn,
	DefenseDownSlash_Turn,
	DefenseDownStab_Turn,
	DefenseDownStrike_Turn,
	ResistDownFire_Count,
	ResistDownIce_Count,
	ResistDownThunder_Count,
	ResistDownLight_Count,
	ResistDownDark_Count,
	ResistDownSlash_Count,
	ResistDownStab_Count,
	ResistDownStrike_Count,
	ResistDownFire_Turn,
	ResistDownIce_Turn,
	ResistDownThunder_Turn,
	ResistDownLight_Turn,
	ResistDownDark_Turn,
	ResistDownSlash_Turn,
	ResistDownStab_Turn,
	ResistDownStrike_Turn,
	CriticalRateUp_Count,
	CriticalRateUpFire_Count,
	CriticalRateUpIce_Count,
	CriticalRateUpThunder_Count,
	CriticalRateUpLight_Count,
	CriticalRateUpDark_Count,
	CriticalRateUpSlash_Count,
	CriticalRateUpStab_Count,
	CriticalRateUpStrike_Count,
	CriticalRateUp_Turn,
	CriticalRateUpFire_Turn,
	CriticalRateUpIce_Turn,
	CriticalRateUpThunder_Turn,
	CriticalRateUpLight_Turn,
	CriticalRateUpDark_Turn,
	CriticalRateUpSlash_Turn,
	CriticalRateUpStab_Turn,
	CriticalRateUpStrike_Turn,
	CriticalDamageUp_Count,
	CriticalDamageUpFire_Count,
	CriticalDamageUpIce_Count,
	CriticalDamageUpThunder_Count,
	CriticalDamageUpLight_Count,
	CriticalDamageUpDark_Count,
	CriticalDamageUpSlash_Count,
	CriticalDamageUpStab_Count,
	CriticalDamageUpStrike_Count,
	CriticalDamageUp_Turn,
	CriticalDamageUpFire_Turn,
	CriticalDamageUpIce_Turn,
	CriticalDamageUpThunder_Turn,
	CriticalDamageUpLight_Turn,
	CriticalDamageUpDark_Turn,
	CriticalDamageUpSlash_Turn,
	CriticalDamageUpStab_Turn,
	CriticalDamageUpStrike_Turn,
	Funnel_Count,
	Fragile_Count,
	Fragile_Turn,
	PowerDownValue_Turn,
	PowerDownRate_Turn,
	DexterityDownValue_Turn,
	DexterityDownRate_Turn,
	WisdomDownValue_Turn,
	WisdomDownRate_Turn,
	ToughnessDownValue_Turn,
	ToughnessDownRate_Turn,
	SpiritDownValue_Turn,
	SpiritDownRate_Turn,
	LuckDownValue_Turn,
	LuckDownRate_Turn,
	ContinuousHpDamageValue_Count,
	ContinuousHpDamageRate_Count,
	ContinuousHpDamageValue_Turn,
	ContinuousHpDamageRate_Turn,
	ContinuousDpDamageValue_Count,
	ContinuousDpDamageRate_Count,
	ContinuousDpDamageValue_Turn,
	ContinuousDpDamageRate_Turn,
	ContinuousDamageValue_Count,
	ContinuousDamageRate_Count,
	ContinuousDamageValue_Turn,
	ContinuousDamageRate_Turn,
	MindEye_Count,
	MindEye_Turn,
	DamageRateUp_Count,
	DamageRateUp_Turn,
	BadStatusResistUp_Count,
	BadStatusResistUp_Turn,
	BadStatusResistUpStun_Count,
	BadStatusResistUpBind_Count,
	BadStatusResistUpConfusion_Count,
	BadStatusResistUpImprison_Count,
	BadStatusResistUpVirus_Count,
	BadStatusResistUpIllusion_Count,
	BadStatusResistUpStun_Turn,
	BadStatusResistUpBind_Turn,
	BadStatusResistUpConfusion_Turn,
	BadStatusResistUpImprison_Turn,
	BadStatusResistUpVirus_Turn,
	BadStatusResistUpIllusion_Turn,
	PowerUpValue_Turn,
	PowerUpRate_Turn,
	DexterityUpValue_Turn,
	DexterityUpRate_Turn,
	WisdomUpValue_Turn,
	WisdomUpRate_Turn,
	ToughnessUpValue_Turn,
	ToughnessUpRate_Turn,
	SpiritUpValue_Turn,
	SpiritUpRate_Turn,
	LuckUpValue_Turn,
	LuckUpRate_Turn,
	AllStatusUpValue_Turn,
	AllStatusUpRate_Turn,
	AllStatusDownValue_Turn,
	AllStatusDownRate_Turn,
	DamageRateResistDown_Turn,
	SignalBuff_Turn,
	DefenseUpDp_Count,
	DefenseUpDpFire_Count,
	DefenseUpDpIce_Count,
	DefenseUpDpThunder_Count,
	DefenseUpDpLight_Count,
	DefenseUpDpDark_Count,
	DefenseUpDpSlash_Count,
	DefenseUpDpStab_Count,
	DefenseUpDpStrike_Count,
	DefenseUpDp_Turn,
	DefenseUpDpFire_Turn,
	DefenseUpDpIce_Turn,
	DefenseUpDpThunder_Turn,
	DefenseUpDpLight_Turn,
	DefenseUpDpDark_Turn,
	DefenseUpDpSlash_Turn,
	DefenseUpDpStab_Turn,
	DefenseUpDpStrike_Turn,
	DefenseDownDp_Count,
	DefenseDownDpFire_Count,
	DefenseDownDpIce_Count,
	DefenseDownDpThunder_Count,
	DefenseDownDpLight_Count,
	DefenseDownDpDark_Count,
	DefenseDownDpSlash_Count,
	DefenseDownDpStab_Count,
	DefenseDownDpStrike_Count,
	DefenseDownDp_Turn,
	DefenseDownDpFire_Turn,
	DefenseDownDpIce_Turn,
	DefenseDownDpThunder_Turn,
	DefenseDownDpLight_Turn,
	DefenseDownDpDark_Turn,
	DefenseDownDpSlash_Turn,
	DefenseDownDpStab_Turn,
	DefenseDownDpStrike_Turn,
	DefenseUpHp_Count,
	DefenseUpHpFire_Count,
	DefenseUpHpIce_Count,
	DefenseUpHpThunder_Count,
	DefenseUpHpLight_Count,
	DefenseUpHpDark_Count,
	DefenseUpHpSlash_Count,
	DefenseUpHpStab_Count,
	DefenseUpHpStrike_Count,
	DefenseUpHp_Turn,
	DefenseUpHpFire_Turn,
	DefenseUpHpIce_Turn,
	DefenseUpHpThunder_Turn,
	DefenseUpHpLight_Turn,
	DefenseUpHpDark_Turn,
	DefenseUpHpSlash_Turn,
	DefenseUpHpStab_Turn,
	DefenseUpHpStrike_Turn,
	DefenseDownHp_Count,
	DefenseDownHpFire_Count,
	DefenseDownHpIce_Count,
	DefenseDownHpThunder_Count,
	DefenseDownHpLight_Count,
	DefenseDownHpDark_Count,
	DefenseDownHpSlash_Count,
	DefenseDownHpStab_Count,
	DefenseDownHpStrike_Count,
	DefenseDownHp_Turn,
	DefenseDownHpFire_Turn,
	DefenseDownHpIce_Turn,
	DefenseDownHpThunder_Turn,
	DefenseDownHpLight_Turn,
	DefenseDownHpDark_Turn,
	DefenseDownHpSlash_Turn,
	DefenseDownHpStab_Turn,
	DefenseDownHpStrike_Turn
}

export enum BuffLimitType {
	Inf,
	None,
	Once,
	Default,
	ThreeTimes
}

export enum ExitConditionType {
	None = 0,
	OneShot,
	Eternal,
	Count,
	PlayerTurnStart,
	PlayerTurnEnd,
	EnemyTurnStart,
	EnemyTurnEnd,
	OverDriveEnd
}

export enum HitType {
	None = 0,
	Main,
	Before,
	After
}

export enum SkillType {
	None = 0,
	AttackNormal = 1,
	DummyType2 = 2,
	DummyType3 = 3,
	DummyType4 = 4,
	DummyType5 = 5,
	DummyType6 = 6,
	DummyType7 = 7,
	DummyType8 = 8,
	DummyType9 = 9,
	AttackSkill = 10,
	AttackBySp = 11,
	AttackRateOfDpHp = 12,
	AttackRateOfMaxDpHp = 13,
	AttackRateOfDp = 14,
	AttackRateOfMaxDp = 15,
	DummyType16 = 16,
	DummyType17 = 17,
	DummyType18 = 18,
	DummyType19 = 19,
	HealDp = 20,
	HealDpRandom = 21,
	HealSp = 22,
	HealSpRandom = 23,
	HealDpRate = 24,
	HealDpRateRandom = 25,
	ReviveDp = 26,
	ReviveDpRandom = 27,
	ReviveDpRate = 28,
	ReviveDpRateRandom = 29,
	AttackUp = 30,
	AttackUpRandom = 31,
	AttackDown = 32,
	AttackDownRandom = 33,
	DefenseDown = 34,
	DefenseDownRandom = 35,
	DefenseUp = 36,
	DefenseUpRandom = 37,
	DummyType38 = 38,
	DummyType39 = 39,
	DummyType40 = 40,
	StunRandom = 41,
	DummyType42 = 42,
	BindRandom = 43,
	DummyType44 = 44,
	DpBreakRandom = 45,
	DummyType46 = 46,
	DummyType47 = 47,
	DummyType48 = 48,
	DummyType49 = 49,
	Funnel = 50,
	FunnelRandom = 51,
	Zone = 52,
	ZoneRandom = 53,
	Provoke = 54,
	ProvokeRandom = 55,
	Invincible = 56,
	InvincibleRandom = 57,
	AdditionalTurn = 58,
	AdditionalTurnRandom = 59,
	SkillRandom = 60,
	Escape = 61,
	Charge = 62,
	AttackToEAoi = 63,
	ReplaceMotion = 64,
	RemoveSpecialStatus = 65,
	Summon = 66,
	SuperIllusion = 67,
	SkillCondition = 68,
	DummyType69 = 69,
	CriticalRateUp = 70,
	CriticalRateUpRandom = 71,
	CriticalRateDown = 72,
	CriticalRateDownRandom = 73,
	CriticalDamageUp = 74,
	CriticalDamageUpRandom = 75,
	CriticalDamageDown = 76,
	CriticalDamageDownRandom = 77,
	DummyType78 = 78,
	DummyType79 = 79,
	OverDrivePointUp = 80,
	OverDrivePointUpRandom = 81,
	DummyType82 = 82,
	DummyType83 = 83,
	DummyType84 = 84,
	DummyType85 = 85,
	DummyType86 = 86,
	DummyType87 = 87,
	DummyType88 = 88,
	DummyType89 = 89,
	ChangeCutInCategory = 90,
	DummyType91 = 91,
	DummyType92 = 92,
	DummyType93 = 93,
	DummyType94 = 94,
	DummyType95 = 95,
	DummyType96 = 96,
	DummyType97 = 97,
	DummyType98 = 98,
	Nothing = 99,
	ResistUp = 100,
	ResistUpRandom = 101,
	ResistDown = 102,
	ResistDownRandom = 103,
	Fragile = 104,
	FragileRandom = 105,
	Confusion = 106,
	ConfusionRandom = 107,
	ConfusionDamage = 108,
	Imprison = 109,
	ImprisonRandom = 110,
	BuffCharge = 111,
	ChargeAttack = 112,
	SpecifySp = 113,
	TokenSet = 114,
	TokenAttack = 115,
	TokenUseAttack = 116,
	TokenChangeTimeline = 117,
	AttackUpPerToken = 118,
	DefenseUpPerToken = 119,
	HealDpByDamage = 120,
	Virus = 121,
	VirusRandom = 122,
	OverDrivePointDown = 123,
	OverDrivePointDownRandom = 124,
	Illusion = 125,
	IllusionRandom = 126,
	AttackUpIncludeNormal = 127,
	Recoil = 128,
	RecoilRandom = 129,
	RegenerationDp = 130,
	BadStatusResistUp = 131,
	BadStatusResistDown = 132,
	SuperAvoidance = 133,
	DummyType134 = 134,
	DummyType135 = 135,
	DummyType136 = 136,
	DummyType137 = 137,
	DummyType138 = 138,
	DummyType139 = 139,
	AttackUpRangeByHit = 140,
	AttackUpRangeByOverDrive = 141,
	OverDrivePointUpByHit = 142,
	DamageRateUpByHit = 143,
	DefenseUpFromEnemyGroup = 144,
	DamageRateResistUp = 145,
	HealDown = 146,
	AttackUpOnlyNormal = 147,
	AdditionalElementOnlyNormal = 148,
	AdditionalElementIncludeNormal = 149,
	AdditionalElement = 150,
	HideObject = 151,
	SkillLimitCountUp = 152,
	OverDriveRateUp = 153,
	OverDriveRateDown = 154,
	AegisChainAttackDown = 155,
	GiveHealUp = 156,
	GiveHealUpFront = 157,
	GiveAttackBuffUp = 158,
	GiveAttackBuffUpFront = 159,
	AttackFixedDamageDefinitely = 160,
	Immortality = 161,
	Cover = 162,
	DamageRateUp = 163,
	Misfortune = 164,
	PowerDownValue = 165,
	PowerDownRate = 166,
	DexterityDownValue = 167,
	DexterityDownRate = 168,
	WisdomDownValue = 169,
	WisdomDownRate = 170,
	ToughnessDownValue = 171,
	ToughnessDownRate = 172,
	SpiritDownValue = 173,
	SpiritDownRate = 174,
	LuckDownValue = 175,
	LuckDownRate = 176,
	ImmortalityDp = 177,
	DamageLimit = 178,
	ContinuousHpDamageValue = 179,
	ContinuousHpDamageRate = 180,
	ContinuousDpDamageValue = 181,
	ContinuousDpDamageRate = 182,
	ContinuousDamageValue = 183,
	ContinuousDamageRate = 184,
	FightingSpirit = 185,
	DefenseUpFromProvoke = 186,
	MindEye = 187,
	Restraint = 188,
	RestraintRandom = 189,
	SandStormZone = 190,
	BadStatusResist = 191,
	SelfDamage = 192,
	PowerUpValue = 193,
	PowerUpRate = 194,
	DexterityUpValue = 195,
	DexterityUpRate = 196,
	WisdomUpValue = 197,
	WisdomUpRate = 198,
	ToughnessUpValue = 199,
	ToughnessUpRate = 200,
	SpiritUpValue = 201,
	SpiritUpRate = 202,
	LuckUpValue = 203,
	LuckUpRate = 204,
	DamageRateChangeAttackSkill = 205,
	TokenSetByAttacked = 206,
	GiveDefenseDebuffUp = 207,
	AllStatusUpValue = 208,
	AllStatusUpRate = 209,
	AllStatusDownValue = 210,
	AllStatusDownRate = 211,
	SuperCover = 212,
	EnableLearningNatureElement = 213,
	DisableLearningNatureElement = 214,
	ApplyLearningNatureElementUp = 215,
	ApplyLearningNatureElementDown = 216,
	DamageSp = 217,
	DamageSpRandom = 218,
	DamageRateResistDown = 219,
	SignalBuff = 220,
	SuperBreak = 221,
	TokenSetByAttacking = 222,
	TokenSetByHealedDp = 223
}

export enum SpecialStatusType {
	None = 0,
	AttackUp,
	AttackDown,
	DefenseDown,
	DefenseUp,
	CriticalRateUp,
	CriticalRateDown,
	CriticalDamageUp,
	CriticalDamageDown,
	ReplaceMotion,
	Stun,
	Bind,
	Provoke,
	Funnel,
	Zone,
	Invincible,
	Escape,
	ResistUp,
	ResistDown,
	BlockSpecialStatus,
	AdditionalTurn,
	ChangeCutInCategory,
	Fragile,
	Confusion,
	Imprison,
	BuffCharge,
	SpecifySp,
	AttackUpPerToken,
	DefenseUpPerToken,
	SuperIllusion,
	Virus,
	Illusion,
	AttackUpIncludeNormal,
	Recoil,
	RegenerationDp,
	BadStatusResistUp,
	BadStatusResistDown,
	SuperAvoidance,
	OverDrivePointPerHitUp,
	DamageRateUp,
	DefenseUpFromEnemyGroup,
	DamageRateResistUp,
	HealDown,
	AttackUpOnlyNormal,
	AdditionalElementOnlyNormal,
	AdditionalElementIncludeNormal,
	AdditionalElement,
	HideObject,
	SkillLimitCountUp,
	OverDrivePointPerHitUpIncludeNormal,
	OverDrivePointPerHitDownIncludeNormal,
	AegisChainAttackDown,
	GiveHealUp,
	GiveHealUpFront,
	GiveAttackBuffUp,
	GiveAttackBuffUpFront,
	Immortality,
	Cover,
	Misfortune,
	PowerDownValue,
	PowerDownRate,
	DexterityDownValue,
	DexterityDownRate,
	WisdomDownValue,
	WisdomDownRate,
	ToughnessDownValue,
	ToughnessDownRate,
	SpiritDownValue,
	SpiritDownRate,
	LuckDownValue,
	LuckDownRate,
	ImmortalityDp,
	DamageLimit,
	ContinuousHpDamage,
	ContinuousDpDamage,
	ContinuousDamage,
	FightingSpirit,
	DefenseUpFromProvoke,
	MindEye,
	Restraint,
	SandStormZone,
	BadStatusResist,
	PowerUpValue,
	PowerUpRate,
	DexterityUpValue,
	DexterityUpRate,
	WisdomUpValue,
	WisdomUpRate,
	ToughnessUpValue,
	ToughnessUpRate,
	SpiritUpValue,
	SpiritUpRate,
	LuckUpValue,
	LuckUpRate,
	TokenSetByAttacked,
	GiveDefenseDebuffUp,
	AllStatusUpValue,
	AllStatusUpRate,
	AllStatusDownValue,
	AllStatusDownRate,
	SuperCover,
	LearningNatureElement,
	ApplyLearningNatureElementUp,
	ApplyLearningNatureElementDown,
	DamageRateResistDown,
	SignalBuff,
	SuperBreak,
	TokenSetByAttacking,
	TokenSetByHealedDp
}

export enum TargetType {
	None = 0,
	Single,
	All,
	Self,
	AllySingle,
	AllyAll,
	AllyFront,
	AllySub,
	Field,
	BothFrontAndSub,
	MinimumDp,
	MaximumDp,
	AllySingleWithoutSelf,
	AllyAllWithoutSelf
}

export enum TimingType {
	None = 0,
	Always,
	OnBattleStart,
	OnPlayerTurnStart,
	OnEnemyTurnStart,
	OnEnemyTurnEnd,
	OnOverdriveStart,
	OnEnemyBroken,
	OnPlayerBroken,
	OnPlayerSelfBroken,
	OnEnemyDestroyed,
	OnEveryTurn,
	OnFirstBattleStart
}

export enum CharacterRole {
	Attacker = 0,
	Breaker,
	Blaster,
	Healer,
	Buffer,
	Debuffer,
	Defender,
	Admiral
}

export enum CharacterRoleURL {
	ATTACKER = 0,
	BREAKER,
	BLASTER,
	HEALER,
	BUFFER,
	DEBUFFER,
	DEFENDER,
	ADMIRAL
}

export enum CharacterRoleGradient {
	Attacker = `hsla(310, 64%, 35%, 0.84)`,
	Breaker = `hsla(358, 64%, 35%, 0.84)`,
	Blaster = `hsla(57, 64%, 35%, 0.84)`,
	Healer = `hsla(171, 64%, 35%, 0.84)`,
	Buffer = `hsla(126, 64%, 35%, 0.84)`,
	Debuffer = `hsla(278, 64%, 35%, 0.84)`,
	Defender = `hsla(214, 64%, 35%, 0.84)`,
	Admiral = `hsla(240, 64%, 35%, 0.84)`
}

export enum WeaponType {
	None = 0,
	DoubleSword,
	Sword,
	Scythe,
	LargeSword,
	Shield,
	Cannon,
	Gun,
	Claw
}

export enum WeaponTypeName {
	None = 0,
	Dualsword,
	Sword,
	Scythe,
	Greatsword,
	Shield,
	Cannon,
	Gun,
	Claw
}

export enum WeaponTypeURL {
	NONE = 0,
	DUALSWORD,
	SWORD,
	SCYTHE,
	GREATSWORD,
	SHIELD,
	CANNON,
	GUN,
	CLAW
}

export enum WeaponAttribute {
	None = 0,
	Slash,
	Thrust,
	Strike,
	Cleave,
	Press,
	Space
}

export enum ElementCategory {
	None = 0,
	Nature,
	Weapon
}

export enum ElementType {
	None = 0,
	Fire,
	Ice,
	Thunder,
	Light,
	Dark,
	Nonelement,
	Slash = 10,
	Stab = 11,
	Strike = 12
}

export enum ElementTypeName {
	None = 0,
	Fire,
	Ice,
	Thunder,
	Light,
	Dark,
	Null,
	Slash = 10,
	Pierce = 11,
	Crush = 12
}

export enum ElementTypeURL {
	NONE = 0,
	FIRE,
	ICE,
	THUNDER,
	LIGHT,
	DARK,
	NULL,
	SLASH = 10,
	STAB = 11,
	STRIKE = 12
}

export enum FieldEffectType {
	Default = 0,
	Fire,
	Ice,
	Thunder,
	Light,
	Dark,
	SandStorm = 20
}

export enum AccessoryCategory {
	None = 0,
	Ring,
	Earring,
	Bracelet,
	Necklace,
	Soul,
	Jewel
}

export enum AccessoryHowToGetType {
	None = 0,
	Shop,
	MemoryStory,
	Event
}

export enum EquipmentConditionType {
	None = 0,
	Character,
	Card
}

export enum ArenaBattleType {
	Arena = 0,
	Prism
}

export enum PrismBattleType {
	None = 0,
	Event,
	Jewel
}

export enum EncountEffectType {
	None = 0,
	Ghost
}

export enum GoalTurnType {
	None = 0,
	Must,
	Bonus
}

export enum ChapterCategory {
	Main = 0,
	Event
}

export enum CharacterSoundType {
	None = 0,
	BattleVictoryStart,
	BattleGrowStart,
	BattleEnemyDeath
}

export enum CharacterVoiceType {
	None = 0,
	EnhanceAbility,
	ReleaseSkill,
	LimitBreak,
	BattleLevelUp,
	BattleLevelUpMax,
	BattleDpDamage,
	BattleHpDamage,
	BattleLose,
	BattleWin,
	BattleWinHard,
	SeraphimCode,
	LiveLose,
	LiveWin,
	LiveWinPerfect,
}

export enum DefineValueType {
	DELTA_COMM_PULL_THRESHOLD = 120000001,
	DELTA_COMM_PUSH_THRESHOLD = 120000002,
	DELTA_COMM_QUEUE_THRESHOLD = 120000003,
	GAME_DAY_OFFSET_HOUR = 120000004,
	GIFT_EXPIRATION_OF_TERM = 120000005,
	CONVERTED_PIECE_NUM_WHEN_CARD_DUPLICATED = 120000006,
	PRISM_BATTLE_DAILY_STAMINA = 120000007,
	GARDEN_EXPEDITION_DAILY_STAMINA = 120000008,
	QUEST_DAILY_STAMINA = 120000009,
	ACTIVITY_DAILY_STAMINA = 120000010,
	STOCK_MAX_ACCESSORY = 120000011,
	STOCK_MAX_BOOSTER = 120000012,
	STOCK_MAX_SPHERE = 120000013,
	GIFT_DELETE_OF_TERM = 120000014,
	REINCARNATION_LEVEL_THRESHOLD = 120000015,
	REINCARNATION_MAX_COUNT = 120000016,
	MOB_HUNT_DAILY_STAMINA = 120000017,
	MAX_LIFE = 120000018,
	LIFE_RECOVERY_TIME_SPAN = 120000019,
	PRISM_BATTLE_CONSUME_TICKET = 120000020,
	GARDEN_EXPEDITION_CONSUME_TICKET = 120000021,
	AUTO_TRAINING_POWER_SAVING_BASE_HOUR = 120000022,
	AUTO_TRAINING_RANK_BONUS_TIME = 120000023,
	AUTO_TRAINING_SAFETY_CLEAR_TIME = 120000024,
	AUTO_TRAINING_CLEAR_TIME_OFFSET = 120000025,
	AUTO_TRAINING_RAND_TIME_MIN = 120000026,
	AUTO_TRAINING_RAND_TIME_MAX = 120000027,
	AGREE_TERMS_VERSION = 120000028,
	MIGRATION_GUIDE_ANNOUNCEMENT_ID = 120000029,
	EXPEDITION_COST_RATE_FOR_BATTLE_TURN = 120000030,
	EXPEDITION_MAX_COST = 120000031,
	MAX_RECEIVABLE_GIFT_NUM = 120000032,
	EXPEDITION_COST_BASE_FOR_BATTLE_TURN = 120000033,
	EXPEDITION_DAMAGE_RATE_BY_COST = 120000034,
	MAX_SPIRIT = 120000035,
	SPIRIT_RECOVERY_TIME_SPAN = 120000036,
	SCORE_ATTACK_BATTLE_CONSUME_SPIRIT = 120000037,
	SCORE_ATTACK_BATTLE_CONSUME_TICKET = 120000038,
	AUTO_EQUIPMENT_INITIAL_SP_COEFFICIENT = 120000039,
	INVITE_RECEIVER_LIMIT = 120000040,
	EXPEDITION_RECOVER_COST_USE_STAMINA = 120000041,
	EXPEDITION_RECOVER_COST_VALUE = 120000042,
	SCORE_ATTACK_HIDE_STRENGTH = 120000043,
	VISIBLE_DECK_NUM = 120000044,
	GATE_BOSS_STAMINA = 120000045,
	MONTHLY_MISSION_ANNOUNCEMENT_ID = 120000046,
	STORY_HARD_MODE_STAMINA = 120000047,
	MISFORTUNE_REF_PARAM_DOWN = 120000048,
	LIMIT_BREAK_POWER_ANNOUNCEMENT_ID = 120000049,
	LIMIT_BREAK_POWER_MAX = 120000050,
	AUTO_BATTLE_RESIST_PRIORITY_RATE = 120000051,
	FIGHTING_SPIRIT_REF_PARAM_UP = 120000052,
	VARIABLE_CHALLENGE_NUMBER_OF_TRIALS = 120000053,
	VARIABLE_CHALLENGE_SAFETY_CLEAR_TIME = 120000054,
	AUTO_EQUIPMENT_CONDITIONAL_PASSIVE_SKILL_FIXED_VALUE = 120000055,
	PRISM_BATTLE_MAX_MULTIPLE_CONSUME_STAMINA = 120000056,
	PRISM_BATTLE_MAX_MULTIPLE_CONSUME_TICKET = 120000057,
	STORY_HARD_MODE_SKIP_TO_BOSS_ANNOUNCEMENT_ID = 120000058,
	FISHING_ROD_FIRST_LEVEL_LIMIT = 120000059,
	LIVE_ANNOUNCEMENT_ID = 120000060,
	LIVE_CONTINUE_USE_STAMINA = 120000061,
	SCRAP_FIELD_EXPEDITION_START_STAMINA = 120000062,
	SCRAP_FIELD_BACK_STAMINA = 120000063,
	FISHING_DEFAULT_COOLER_BOX_AMOUNT = 120000064,
	NORMAL_ATTACK_OVER_DRIVE_GAUGE_MINIMUM_GUARANTEE = 120000065,
	LIVE_RANKING_BOTTOM_RANK_BORDER = 120000066,
	LIVE_RANKING_UPPER_LIMIT_OF_DATA_COUNT = 120000067,
	LIVE_RANKING_GOLD_RANK_BORDER = 120000068,
	LIVE_RANKING_SILBER_RANK_BORDER = 120000069,
	LIVE_RANKING_BRONZE_RANK_BORDER = 120000070,
	FISHING_FAILD_EXP_RATE = 120000071
}

export enum EncountCutInCondition {
	Normal = 0,
	Rare,
	AC07,
	MC04,
	MC04_Rare,
	AC07_Day3
}

export enum ExpeditionEnchantType {
	None = 0,
	SlotExpansion,
	RecoverCost,
	HealDp,
	ReviveDp,
	ExtraTurn,
	PassiveSkill
}

export enum FieldCutInType {
	None = 0,
	Free,
	Symbol,
	Item,
	FieldEnemyWarning,
	FieldEnemyEmergency
}

export enum ItemCategory {
	Material = 0,
	SC = 3,
	Piece = 5,
	Enhance = 6,
	Exp = 9,
	LevelUpTicket = 11,
	LotteryTicket = 12,
	LotteryPoint = 13,
	Reincarnation = 14,
	EventToken = 15,
	GGP = 16,
	Jewel = 17,
	ExtraReincarnation = 18,
	ReincarnateCancel = 19,
	IceCandy = 20,
	MusicRecord = 21,
	Scrap = 22,
	AC14_Material = 23,
	AC14_Processing = 24,
	AC14_Cooking = 25,
	FishingBait = 26,
	CoolerBox = 27,
	Fish = 28,
	FishingRod = 29
}